spring.application.name=order-service
server.port=8081

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces

logging.level.root=INFO
logging.level.com.ecom=DEBUG

services.inventory-service.url=http://inventory-service:8082
services.notification-service.url=http://notification-service:8083
